version: "3"

services:
  iscva-backend:
    image: "florant/iscvam-backend"
    ports:
      - "8002:8002"
    volumes:
      - "./backend/config/datasets.json:/app/datasets.json"
      - "./datasets:/app/data/datasets"
    command: ["node", "app.js"]

  iscva-frontend:
    image: "florant/iscvam-frontend"
    ports:
      - "3001:80"
    volumes:
      - "./frontend/config/app-settings.json:/usr/share/nginx/html/app-settings.json"
    depends_on:
      - iscva-backend
